/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

#ifdef __cplusplus
extern "C" {
#endif
// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghConsole1;
extern GHandle ghLabel1;
extern GHandle ghTestButton;

// Function Prototypes
void guiCreate(void);

void guiShowPage(unsigned pageIndex);

void guiEventLoop(void);

#ifdef __cplusplus
}
#endif
#endif /* _GUI_H_ */

